import type { LucideIcon } from "lucide-react";
import {
  Sparkles,
  SprayCan,
  CookingPot,
  Utensils,
  ShoppingCart,
  Droplet,
  Shirt,
  Dog,
  Cat,
  Flower2,
  Trash2,
  Wrench,
  Hammer,
  Paintbrush,
  Bed,
  Bath,
  Car,
  Bike,
  Dumbbell,
  Pill,
  Heart,
  Baby,
  BookOpen,
  Mail,
  Phone,
  Wifi,
  Zap,
  Thermometer,
  Fan,
  Refrigerator,
  WashingMachine,
  Lamp,
  Key,
  Package,
  Recycle,
  Leaf,
} from "lucide-react";

/** Static map of common household icons — renders instantly (no lazy load). */
const STATIC_ICONS: Record<string, LucideIcon> = {
  sparkles: Sparkles,
  "spray-can": SprayCan,
  "cooking-pot": CookingPot,
  utensils: Utensils,
  "shopping-cart": ShoppingCart,
  droplet: Droplet,
  shirt: Shirt,
  dog: Dog,
  cat: Cat,
  "flower-2": Flower2,
  "trash-2": Trash2,
  wrench: Wrench,
  hammer: Hammer,
  paintbrush: Paintbrush,
  bed: Bed,
  bath: Bath,
  car: Car,
  bike: Bike,
  dumbbell: Dumbbell,
  pill: Pill,
  heart: Heart,
  baby: Baby,
  "book-open": BookOpen,
  mail: Mail,
  phone: Phone,
  wifi: Wifi,
  zap: Zap,
  thermometer: Thermometer,
  fan: Fan,
  refrigerator: Refrigerator,
  "washing-machine": WashingMachine,
  lamp: Lamp,
  key: Key,
  package: Package,
  recycle: Recycle,
  leaf: Leaf,
};

/**
 * Get a statically-imported icon component by name.
 * Returns null if the name is not in the curated set (use DynamicIcon as fallback).
 */
export function getTaskIcon(name: string | null): LucideIcon | null {
  if (!name) return null;
  return STATIC_ICONS[name] ?? null;
}
